// Auto-generated by: pnpm supabase gen types typescript --project-id YOUR_PROJECT_ID
// Replace this file by running the command above after creating your Supabase project.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
